# Generated by Django 3.2 on 2021-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob_no', models.IntegerField()),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('EN', 'Electrical Engineering')], default='CS', max_length=2)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=50)),
            ],
        ),
    ]
