# Generated by Django 3.2 on 2021-06-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mob_no', models.IntegerField(max_length=10)),
                ('branch', models.CharField(choices=[], default='CS', max_length=2)),
                ('year', models.IntegerField(choices=[], default='1', max_length=1)),
                ('sec', models.CharField(choices=[], default='A', max_length=50)),
            ],
        ),
    ]
