# Generated by Django 3.2 on 2021-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhikash_app', '0003_auto_20210605_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('EN', 'Electrical Engineering')], default='CS', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
