# Generated by Django 3.2 on 2021-06-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abhikash_app', '0004_auto_20210606_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
